---
title: "A collection of useful functions: welcome to the `broTools` package!"
author: "Bruno Rodrigues"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

`broTools` is a package that includes some useful functions to make the life of the DMD at 
STATEC easier. Here is the list of the included functions:

* `all_data_to_upper()`
* `modal_value()`
* `multi_join()`
* `read_list()`

### Change the letter case of the column names of a list of datasets to uppercase with `all_data_to_upper()`

This function changes the letter case of the column names of the datasets stored in a list to 
upper case. This is useful for merging datasets with the same column names, but with different 
letter cases.

### Get the mode a list of number or characters thanks to `modal_value()`

As surprising as it may seem, R does not have a function to compute the mode of a list of 
observations. This function solves this, but the implementation is very basic for now. For example
in the case of a tie, it only returns the first of the two modes.

### Join a list of datasets into one single dataset using `multi_join()`

`multi_join()` solves the problem of merging a lot of datasets together. It takes a list of datasets
as an input, and outputs a `tibble` (an enhanced version of base R's `data.frames`).

### Read a lot of datasets at once easily with `read_list()`

`read_list()` works by giving it a list of datasets in your current working directory and a read
function, such as `readr::read_csv()` in case you want to read `.csv` files and puts them in a 
list. You can then use the above functions on this list of datasets.

